### ISSUE TITLE
Use blocks to scope restrictions

### ISSUE THREAD

**Issue by MrTheWalrus** [dmcouncil/data_works#11]
When using the `set_restriction` feature, I frequently find that I'm doing something like this:

```
def thing
  @data.set_restriction(for_model: :year, to: year)
  new_thing = @data.add_thing
  @data.clear_restriction_for(:year)
  new_thing
end
```

It would be convenient if I could instead do something like this:

```
def thing
  @data.with_restrictions(year: year) do
    @data.add_thing
  end
end
```

**Comment by ludamillion** [comment]
Resolved with 9128c014aae44268e9f3589a6bd32d0e672f55ed
